language: node_js

node_js:
- stable

script:
- npm run start

deploy:
  provider: releases
  api_key:
    secure: R6D1l8L4+ie+U0kmaxofkW+5ogyzDuwCocXcb56ALU9afrKcTjxVHpHc84eFpCKP3c4lwUI/89wiIvImfLU1893G/NqwonIn0kYQ0Uo3gkg/p4nzHQxjOTSNMokD8qX+wpEOz3hDAlDgWyLOJOmImRezYPAxmd8qSPjI4InDMb6ldbS1QK6GXMbitskrxjDHqUyEKK0ODa3r4v+cy72ps4wUnlRoPXf90T4OUOX3h04yLvobzlKLEo7MzBmdRXhBQWGYA5KbnPIo8WJQyrzI6zSNtWMJ5SikoqlZSoZi2VztL8NDJtM35tLEuby8w2qdu9mGJGV/61IdxIMYqKhBSZWc5F3MgeR0MWNXLcGpLZ5Wn/0FlxZFXswmAL8mB1xyQCQ9YlGkiqO8f89qY26pS5R4hNteV4HFHVPEXHlY9R1PeqrCxHo2lL6i9+LQ9ZGMha00+sW3FQOmJeOE1X3TrKelSYu3VTK+BXXboiqByf9dWV64KJH3+B4ExJFUXUw09nVeJGeA1aQ+4EPJrb5fSpNKDfHTEgyvXoPdo2XTc7K3QcrTVmgS9dUcMA/+6HMCrd0zfg9NIGAZMcga6HU8EcX1UYBGp9kxS8jSifkd1dFQ2MsWubbU4D9+luPNVoR7b85k3Iv8vRx4hzDZ+jIDy60w3TXu2rx9vUg8FNOi1Mw=
  file_glob: true
  file: build/build_*.tar.gz
  skip_cleanup: true
  on:
    tags: true
